field-forms/objects/Form_Page__c/Form_Page__c.object-meta.xml
<CustomObject>
    <label>Form Page</label>
    <nameField>
        <label>Form Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

field-forms/objects/Form_Page__c/fields/Form_Template__c.field-meta.xml
<CustomField>
    <fullName>Form_Template__c</fullName>
    <label>Form Template</label>
    <referenceTo>Form_Template__c</referenceTo>
    <relationshipLabel>Form Pages</relationshipLabel>
    <relationshipName>Form_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

field-forms/objects/Form_Question__c/Form_Question__c.object-meta.xml
<CustomObject>
    <label>Form Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

field-forms/objects/Form_Question__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <label>Column</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

field-forms/objects/Form_Question__c/fields/Conditions__c.field-meta.xml
<CustomField>
    <fullName>Conditions__c</fullName>
    <label>Conditions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Form_Page__c.field-meta.xml
<CustomField>
    <fullName>Form_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Page</label>
    <referenceTo>Form_Page__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>Form_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Form_Section__c.field-meta.xml
<CustomField>
    <fullName>Form_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Section</label>
    <referenceTo>Form_Section__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>Form_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Form_Template__c.field-meta.xml
<CustomField>
    <fullName>Form_Template__c</fullName>
    <label>Form Template</label>
    <referenceTo>Form_Template__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Min__c.field-meta.xml
<CustomField>
    <fullName>Min__c</fullName>
    <label>Min</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Slider_Size__c.field-meta.xml
<CustomField>
    <fullName>Slider_Size__c</fullName>
    <label>Slider Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>x-small</fullName>
            </value>
            <value>
                <fullName>small</fullName>
            </value>
            <value>
                <fullName>medium</fullName>
            </value>
            <value>
                <fullName>large</fullName>
            </value>
            <value>
                <fullName>full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

field-forms/objects/Form_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Form_Question_Answer_types</valueSetName>
    </valueSet>
</CustomField>

field-forms/objects/Form_Section__c/Form_Section__c.object-meta.xml
<CustomObject>
    <label>Form Section</label>
    <nameField>
        <label>Form Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

field-forms/objects/Form_Section__c/fields/Columns__c.field-meta.xml
<CustomField>
    <fullName>Columns__c</fullName>
    <label>Columns</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

field-forms/objects/Form_Section__c/fields/Form_Page__c.field-meta.xml
<CustomField>
    <fullName>Form_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Page</label>
    <referenceTo>Form_Page__c</referenceTo>
    <relationshipLabel>Form Sections</relationshipLabel>
    <relationshipName>Form_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

field-forms/objects/Form_Section__c/fields/Form_Section__c.field-meta.xml
<CustomField>
    <fullName>Form_Section__c</fullName>
    <label>Form Section</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

field-forms/objects/Form_Section__c/fields/Form_Template__c.field-meta.xml
<CustomField>
    <fullName>Form_Template__c</fullName>
    <label>Form Template</label>
    <referenceTo>Form_Template__c</referenceTo>
    <relationshipLabel>Form Sections</relationshipLabel>
    <relationshipName>Form_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

field-forms/objects/Form_Section__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Section&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Section</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

field-forms/objects/Form_Setting__mdt/fields/Display_Label__c.field-meta.xml
<CustomField>
    <fullName>Display_Label__c</fullName>
    <label>Display Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

field-forms/objects/Form_Setting__mdt/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <label>Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

field-forms/objects/Form_Setting__mdt/fields/Structure__c.field-meta.xml
<CustomField>
    <fullName>Structure__c</fullName>
    <label>Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Component</fullName>
                <default>true</default>
                <label>Component</label>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>Page</fullName>
            </value>
            <value>
                <fullName>Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

field-forms/objects/Form_Setting_Field__mdt/Form_Setting_Field__mdt.object-meta.xml
<CustomObject>
    <label>Form Setting Field</label>
    <pluralLabel>Form Setting Fields</pluralLabel>
</CustomObject>

field-forms/objects/Form_Setting_to_Field__mdt/Form_Setting_to_Field__mdt.object-meta.xml
<CustomObject>
    <label>Form Setting to Field</label>
    <pluralLabel>Form Setting to Fields</pluralLabel>
</CustomObject>

field-forms/objects/Form_Setting_to_Field__mdt/fields/Form_Setting__c.field-meta.xml
<CustomField>
    <fullName>Form_Setting__c</fullName>
    <label>Form Setting</label>
    <referenceTo>Form_Setting__mdt</referenceTo>
    <relationshipLabel>Form Setting to Fields</relationshipLabel>
    <relationshipName>Form_Setting_to_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

field-forms/objects/Form_Setting_to_Field__mdt/fields/Form_Setting_Field__c.field-meta.xml
<CustomField>
    <fullName>Form_Setting_Field__c</fullName>
    <label>Form Setting Field</label>
    <referenceTo>Form_Setting_Field__mdt</referenceTo>
    <relationshipLabel>Form Setting to Fields</relationshipLabel>
    <relationshipName>Form_Setting_to_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

field-forms/objects/Form_Template__c/Form_Template__c.object-meta.xml
<CustomObject>
    <label>Form Template</label>
    <nameField>
        <label>Form Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

field-forms/objects/Form_Template__c/fields/Indicator_Type__c.field-meta.xml
<CustomField>
    <fullName>Indicator_Type__c</fullName>
    <label>Indicator Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vertical</fullName>
            </value>
            <value>
                <fullName>Horizontal</fullName>
            </value>
            <value>
                <fullName>Path</fullName>
            </value>
            <value>
                <fullName>Bar</fullName>
            </value>
            <value>
                <fullName>VertNav</fullName>
            </value>
            <value>
                <fullName>Ring</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

field-forms/globalValueSets/Form_Question_Answer_types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Text</fullName>
    </customValue>
    <customValue>
        <fullName>Text Area</fullName>
    </customValue>
    <customValue>
        <fullName>Multiple Choice</fullName>
    </customValue>
    <customValue>
        <fullName>Checkboxes</fullName>
    </customValue>
    <customValue>
        <fullName>Dropdown</fullName>
    </customValue>
    <customValue>
        <fullName>Radio Buttons</fullName>
    </customValue>
    <customValue>
        <fullName>Date</fullName>
    </customValue>
    <customValue>
        <fullName>Time</fullName>
    </customValue>
    <customValue>
        <fullName>Number</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Slider</fullName>
    </customValue>
    <customValue>
        <fullName>File Upload</fullName>
    </customValue>
    <customValue>
        <fullName>Geolocation</fullName>
    </customValue>
    <customValue>
        <fullName>Toggle</fullName>
    </customValue>
    <customValue>
        <fullName>Signature</fullName>
    </customValue>
    <customValue>
        <fullName>Checkbox</fullName>
    </customValue>
    <customValue>
        <fullName>Scan Barcode</fullName>
    </customValue>
    <customValue>
        <fullName>Display Text</fullName>
    </customValue>
    <customValue>
        <fullName>Calculation</fullName>
    </customValue>
    <customValue>
        <fullName>Pass Fail NA</fullName>
        <label>Pass / Fail / N-A</label>
    </customValue>
    <customValue>
        <fullName>Counter</fullName>
    </customValue>
    <customValue>
        <fullName>Date Time</fullName>
        <label>Date + Time</label>
    </customValue>
    <customValue>
        <fullName>Currency</fullName>
    </customValue>
    <customValue>
        <fullName>Lookup</fullName>
        <label>Lookup (Salesforce record)</label>
    </customValue>
    <customValue>
        <fullName>Repeatable</fullName>
        <label>Repeatable (add another row)</label>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
        <label>Checklist (Pass / Fail / N-A per row)</label>
    </customValue>
    <description>Used for form question and answer types</description>
    <masterLabel>Form Question/Answer types</masterLabel>
</GlobalValueSet>

field-forms/classes/neuraFormBuilderController.cls
public with sharing class neuraFormBuilderController {
    @AuraEnabled(cacheable=true)
    public static List<Form_Setting_to_Field__mdt> getAllAttributes() {
        List<Form_Setting_to_Field__mdt> formSettingToField = [SELECT MasterLabel, Form_Setting__r.Label, Form_Setting_Field__r.Label FROM Form_Setting_to_Field__mdt];
        
        // Create a new list to store modified results
        List<Form_Setting_to_Field__mdt> modifiedFormSettingToField = new List<Form_Setting_to_Field__mdt>();
        
        // Get the namespace prefix once
        String namespacePrefix = NeuraFormUtils.getNamespacePrefix();
        
        for (Form_Setting_to_Field__mdt fsf : formSettingToField) {
            // Create a deep copy of the object to modify
            Form_Setting_to_Field__mdt fsfCopy = fsf.clone(false, false, false, false);
            
            // Check if the Label already starts with the namespace prefix
            if (!fsfCopy.Form_Setting_Field__r.Label.startsWith(namespacePrefix)) {
                fsfCopy.Form_Setting_Field__r.Label = namespacePrefix + fsf.Form_Setting_Field__r.Label;
            }
            
            modifiedFormSettingToField.add(fsfCopy);
        }
        
        return modifiedFormSettingToField;
    }

    @AuraEnabled(cacheable=false)
    public static FormWrapper getFormDetails(Id formTemplateId){
        if (formTemplateId == null) {
            return null;
        }
        // LIMIT 1 + list assignment so an unknown / soft-deleted Id returns
        // null instead of throwing QueryException at the client.
        List<Form_Template__c> templates = [
            SELECT Id, Name, Indicator_Type__c
            FROM Form_Template__c
            WHERE Id = :formTemplateId
            LIMIT 1
        ];
        if (templates.isEmpty()) {
            return null;
        }
        Form_Template__c ft = templates[0];
        List<Form_Page__c> pages = [SELECT Id, Name, Order__c, Title__c, Form_Template__c, Conditions__c FROM Form_Page__c WHERE Form_Template__c = :ft.Id ORDER BY Order__c ASC];
       // List<Form_Section__c> sections = [SELECT Id, Name, Type__c, Title__c, Order__c, Form_Template__c, Form_Page__c, Columns__c, Sho FROM Form_Section__c WHERE Form_Template__c = :ft.Id ORDER BY Order__c ASC];
        
        SObjectType sectionObjectType = Form_Section__c.SObjectType;
        String sectionWhereClause = 'Form_Template__c = \'' + ft.Id + '\'';
        List<SObject> sections = dynamicQuery(sectionObjectType, sectionWhereClause);

        // Cast the result to the specific SObject type if needed
        List<Form_Section__c> formattedSections = (List<Form_Section__c>) sections;

        SObjectType questionObjectType = Form_Question__c.SObjectType;
        String questionWhereClause = 'Form_Template__c = \'' + ft.Id + '\'';
        List<SObject> questions = dynamicQuery(questionObjectType, questionWhereClause);

        // Cast the result to the specific SObject type if needed
        List<Form_Question__c> formattedQuestions = (List<Form_Question__c>) questions;
        
        //List<Form_Question__c> questions = [SELECT Id, Name, Type__c, Order__c, Question__c, Column__c, Form_Template__c, Form_Section__c, Form_Page__c, Value_Set__c, Required__c, Slider_Size__c, Min__c, Max__c, Slider_Step__c FROM Form_Question__c WHERE Form_Template__c = :ft.Id];

        return new FormWrapper(ft, pages, formattedSections, formattedQuestions);
    }

    private static List<SObject> dynamicQuery(SObjectType sObjectType, String whereClause) {
        // Get the metadata for the given SObjectType
        DescribeSObjectResult describeResult = sObjectType.getDescribe();

        // List to hold field names
        List<String> fieldNames = new List<String>();

        // Iterate over all fields and add them to the fieldNames list, excluding system fields
        for (Schema.SObjectField field : describeResult.fields.getMap().values()) {
            Schema.DescribeFieldResult fieldDescribe = field.getDescribe();

            // Check if the field is not a system field
            if (!fieldDescribe.isCalculated() && !fieldDescribe.isAutoNumber()) {
                // Add field name to the list
                fieldNames.add(fieldDescribe.getName());
            }
        }

        // Construct the dynamic query
        String queryString = 'SELECT ' + String.join(fieldNames, ', ') + ' FROM ' + sObjectType.getDescribe().getName();
        if (String.isNotBlank(whereClause)) {
            queryString += ' WHERE ' + whereClause;
        }

        queryString += ' ORDER BY Order__c ASC';

        // Execute the query and return the result
        return Database.query(queryString);
    }

    @AuraEnabled(cacheable=false)
    public static List<Form_Setting__mdt> getFormMetadata(){
        return [SELECT Id, Label, Icon__c, DeveloperName, MasterLabel, Structure__c, Display_Label__c, Order__c FROM Form_Setting__mdt ORDER BY Order__c ASC];
    }

    @AuraEnabled(cacheable=false)
    public static List<SObject> processFormUpdate(List<SObject> toCreate, List<SObject> toUpdate, List<Id> toDelete){
        // Wrap every DML so the actual error message reaches the LWC. Raw
        // DmlException propagates as a generic "Script-thrown exception" /
        // "Unknown error" - useless when an admin is trying to find the bad
        // record. We rethrow as AuraHandledException with .setMessage() so
        // the LWC's catch block sees the real cause.
        try {
            if (toDelete != null && toDelete.size() > 0) {
                deleteRecordsFromList(toDelete);
            }
            if (toCreate != null && toCreate.size() > 0) {
                insert toCreate;
            }
            if (toUpdate != null && toUpdate.size() > 0) {
                update toUpdate;
            }
            return toCreate;
        } catch (DmlException e) {
            String msg = e.getMessage();
            // For each failed row, append the field-level detail. DmlException
            // exposes per-row errors via getDmlMessage / getDmlFields.
            List<String> rowDetails = new List<String>();
            for (Integer i = 0; i < e.getNumDml(); i++) {
                String fields = e.getDmlFields(i) != null
                    ? String.join(e.getDmlFieldNames(i), ', ')
                    : '';
                rowDetails.add(
                    'Row ' + i + ': ' + e.getDmlMessage(i)
                    + (String.isNotBlank(fields) ? ' (fields: ' + fields + ')' : '')
                );
            }
            String full = String.isNotBlank(msg) ? msg : 'DML error';
            if (!rowDetails.isEmpty()) {
                full += ' - ' + String.join(rowDetails, '; ');
            }
            AuraHandledException ahe = new AuraHandledException(full);
            ahe.setMessage(full);
            throw ahe;
        } catch (Exception e) {
            AuraHandledException ahe = new AuraHandledException(e.getMessage());
            ahe.setMessage(e.getMessage());
            throw ahe;
        }
    }
    @AuraEnabled(cacheable=false)
    public static Form_Template__c processFormRecord(Form_Template__c toCreate, Form_Template__c toUpdate){
        try {
            if (toCreate != null) {
                insert toCreate;
                return toCreate;
            }
            if (toUpdate != null) {
                update toUpdate;
                return toUpdate;
            }
            return null;
        } catch (Exception e) {
            // Same pattern as processFormUpdate - rethrow as AuraHandledException
            // with setMessage so the LWC sees the real error.
            AuraHandledException ahe = new AuraHandledException(e.getMessage());
            ahe.setMessage(e.getMessage());
            throw ahe;
        }
    }
    
    @AuraEnabled(cacheable=false)
    public static List<Form_Page__c> processPageRecords(List<Form_Page__c> toCreate, List<Form_Page__c> toUpdate, List<Id> toDelete){
        return (List<Form_Page__c>) processFormUpdate(toCreate, toUpdate, toDelete);
    }

    @AuraEnabled(cacheable=false)
    public static List<Form_Section__c> processSectionRecords(List<Form_Section__c> toCreate, List<Form_Section__c> toUpdate, List<Id> toDelete){
        return (List<Form_Section__c>) processFormUpdate(toCreate, toUpdate, toDelete);
    }

    @AuraEnabled(cacheable=false)
    public static List<Form_Question__c> processQuestionRecords(List<Form_Question__c> toCreate, List<Form_Question__c> toUpdate, List<Id> toDelete){
        return (List<Form_Question__c>) processFormUpdate(toCreate, toUpdate, toDelete);
    }

    public static void deleteRecordsFromList(List<Id> toDeleteIds){
        // allOrNone=false so partial-success reporting actually works; with
        // allOrNone=true, any failure throws DmlException and the per-result
        // error loop below never executes. The first failure is rethrown as
        // an AuraHandledException so the LWC sees a usable error message.
        Database.DeleteResult[] deleteResults = Database.delete(toDeleteIds, false);
        List<String> errorMessages = new List<String>();
        for (Database.DeleteResult dr : deleteResults) {
            if (!dr.isSuccess()) {
                for (Database.Error err : dr.getErrors()) {
                    String msg = err.getStatusCode() + ': ' + err.getMessage()
                        + ' (fields: ' + err.getFields() + ')';
                    System.debug(LoggingLevel.ERROR, msg);
                    errorMessages.add(msg);
                }
            }
        }
        if (!errorMessages.isEmpty()) {
            throw new AuraHandledException(
                'Failed to delete ' + errorMessages.size() + ' record(s): '
                + String.join(errorMessages, '; ')
            );
        }
    }

    public class FormWrapper{
        @AuraEnabled
        public Form_Template__c formTemplate;
        @AuraEnabled
        public List<Form_Page__c> pages;
        @AuraEnabled
        public List<Form_Section__c> sections;
        @AuraEnabled
        public List<Form_Question__c> questions;

        public FormWrapper(Form_Template__c formTemplate, List<Form_Page__c> pages, List<Form_Section__c> sections, List<Form_Question__c> questions){
            this.formTemplate = formTemplate;
            this.pages = pages;
            this.sections = sections;
            this.questions = questions;
        }
    }


}