field-forms/objects/FieldForms_Configuration__c/FieldForms_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Handles configuration attributes of FieldForms</description>
    <label>FieldForms Configuration</label>
</CustomObject>

field-forms/objects/FieldForms_Configuration__c/fields/Disable_Form_Template_JSON_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Form_Template_JSON_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Disables the form templates compiling the JSON of the pages, sections, questions and conditions. This should be used during import and export exercises when dealing with large forms.</description>
    <inlineHelpText>Disables the form templates compiling the JSON of the pages, sections, questions and conditions. This should be used during import and export exercises when dealing with large forms.</inlineHelpText>
    <label>Disable Form Template JSON Trigger</label>
    <type>Checkbox</type>
</CustomField>

field-forms/objects/Form_Page__c/Form_Page__c.object-meta.xml
<CustomObject>
    <label>Form Page</label>
    <nameField>
        <label>Form Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Pages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

field-forms/objects/Form_Page__c/fields/Form_Template__c.field-meta.xml
<CustomField>
    <fullName>Form_Template__c</fullName>
    <label>Form Template</label>
    <referenceTo>Form_Template__c</referenceTo>
    <relationshipLabel>Form Pages</relationshipLabel>
    <relationshipName>Form_Pages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

field-forms/objects/Form_Question__c/Form_Question__c.object-meta.xml
<CustomObject>
    <label>Form Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Form Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

field-forms/objects/Form_Question__c/fields/Conditions__c.field-meta.xml
<CustomField>
    <fullName>Conditions__c</fullName>
    <label>Conditions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Display_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Display_Rich_Text__c</fullName>
    <label>Display Rich Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/External_Reference__c.field-meta.xml
<CustomField>
    <fullName>External_Reference__c</fullName>
    <externalId>true</externalId>
    <label>External Reference</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Form_Page__c.field-meta.xml
<CustomField>
    <fullName>Form_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Page</label>
    <referenceTo>Form_Page__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>Form_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Form_Section__c.field-meta.xml
<CustomField>
    <fullName>Form_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Section</label>
    <referenceTo>Form_Section__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>Form_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Form_Template__c.field-meta.xml
<CustomField>
    <fullName>Form_Template__c</fullName>
    <label>Form Template</label>
    <referenceTo>Form_Template__c</referenceTo>
    <relationshipLabel>Form Questions</relationshipLabel>
    <relationshipName>Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Include_Comment__c.field-meta.xml
<CustomField>
    <fullName>Include_Comment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Comment</label>
    <type>Checkbox</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Label_Visible__c.field-meta.xml
<CustomField>
    <fullName>Label_Visible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Label Visible</label>
    <type>Checkbox</type>
</CustomField>

field-forms/objects/Form_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Form_Question_Answer_types</valueSetName>
    </valueSet>
</CustomField>

field-forms/objects/Form_Section__c/Form_Section__c.object-meta.xml
<CustomObject>
    <label>Form Section</label>
    <nameField>
        <label>Form Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

field-forms/objects/Form_Section__c/fields/Form_Page__c.field-meta.xml
<CustomField>
    <fullName>Form_Page__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Page</label>
    <referenceTo>Form_Page__c</referenceTo>
    <relationshipLabel>Form Sections</relationshipLabel>
    <relationshipName>Form_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

field-forms/objects/Form_Section__c/fields/Form_Section__c.field-meta.xml
<CustomField>
    <fullName>Form_Section__c</fullName>
    <label>Form Section</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

field-forms/objects/Form_Section__c/fields/Form_Template__c.field-meta.xml
<CustomField>
    <fullName>Form_Template__c</fullName>
    <label>Form Template</label>
    <referenceTo>Form_Template__c</referenceTo>
    <relationshipLabel>Form Sections</relationshipLabel>
    <relationshipName>Form_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

field-forms/objects/Form_Section__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;Section&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Section</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

field-forms/objects/Form_Template__c/Form_Template__c.object-meta.xml
<CustomObject>
    <label>Form Template</label>
    <nameField>
        <label>Form Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

field-forms/objects/Form_Template__c/fields/External_Reference__c.field-meta.xml
<CustomField>
    <fullName>External_Reference__c</fullName>
    <externalId>true</externalId>
    <label>External Reference</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

field-forms/objects/Form_Template__c/fields/Pages_JSON__c.field-meta.xml
<CustomField>
    <fullName>Pages_JSON__c</fullName>
    <label>Pages JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

field-forms/objects/Form_Template__c/fields/Questions_JSON__c.field-meta.xml
<CustomField>
    <fullName>Questions_JSON__c</fullName>
    <label>Questions JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

field-forms/objects/Form_Template__c/fields/Sections_JSON__c.field-meta.xml
<CustomField>
    <fullName>Sections_JSON__c</fullName>
    <label>Sections JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

field-forms/globalValueSets/Form_Question_Answer_types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Text</fullName>
    </customValue>
    <customValue>
        <fullName>Text Area</fullName>
    </customValue>
    <customValue>
        <fullName>Multiple Choice</fullName>
    </customValue>
    <customValue>
        <fullName>Checkboxes</fullName>
    </customValue>
    <customValue>
        <fullName>Dropdown</fullName>
    </customValue>
    <customValue>
        <fullName>Radio Buttons</fullName>
    </customValue>
    <customValue>
        <fullName>Date</fullName>
    </customValue>
    <customValue>
        <fullName>Time</fullName>
    </customValue>
    <customValue>
        <fullName>Number</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Slider</fullName>
    </customValue>
    <customValue>
        <fullName>File Upload</fullName>
    </customValue>
    <customValue>
        <fullName>Geolocation</fullName>
    </customValue>
    <customValue>
        <fullName>Toggle</fullName>
    </customValue>
    <customValue>
        <fullName>Signature</fullName>
    </customValue>
    <customValue>
        <fullName>Checkbox</fullName>
    </customValue>
    <customValue>
        <fullName>Scan Barcode</fullName>
    </customValue>
    <customValue>
        <fullName>Display Text</fullName>
    </customValue>
    <customValue>
        <fullName>Calculation</fullName>
    </customValue>
    <customValue>
        <fullName>Pass Fail NA</fullName>
        <label>Pass / Fail / N-A</label>
    </customValue>
    <customValue>
        <fullName>Counter</fullName>
    </customValue>
    <customValue>
        <fullName>Date Time</fullName>
        <label>Date + Time</label>
    </customValue>
    <customValue>
        <fullName>Currency</fullName>
    </customValue>
    <customValue>
        <fullName>Lookup</fullName>
        <label>Lookup (Salesforce record)</label>
    </customValue>
    <customValue>
        <fullName>Repeatable</fullName>
        <label>Repeatable (add another row)</label>
    </customValue>
    <customValue>
        <fullName>Checklist</fullName>
        <label>Checklist (Pass / Fail / N-A per row)</label>
    </customValue>
    <description>Used for form question and answer types</description>
    <masterLabel>Form Question/Answer types</masterLabel>
</GlobalValueSet>

field-forms/classes/NeuraFormExportControllerTest.cls
@isTest
public class NeuraFormExportControllerTest {
    
    // Utility method to create test data for Form_Template__c and related objects
    static void createTestData() {
        Form_Template__c template = new Form_Template__c(Name='Test Template');
        insert template;
        System.debug('Test Template Id: ' + template.Id);
        
        Form_Page__c page = new Form_Page__c(Name='Test Page', Form_Template__c=template.Id);
        insert page;
        
        Form_Section__c section = new Form_Section__c(Name='Test Section', Form_Template__c=template.Id, Form_Page__c=page.Id);
        insert section;
        
        List<Form_Question__c> questions = new List<Form_Question__c>();
        Form_Question__c question = new Form_Question__c(Question__c='Test Question', Form_Template__c=template.Id, Form_Section__c=section.Id);
        Form_Question__c question2 = new Form_Question__c(Question__c='Test Question 2', Form_Template__c=template.Id, Form_Section__c=section.Id);
        questions.add(question);
        questions.add(question2);
        insert questions;
    }

    static void setCustomSetting(){
        FieldForms_Configuration__c cusSetting = new FieldForms_Configuration__c();
        cusSetting.Disable_Form_Template_JSON_Trigger__c = true; 
        insert cusSetting;
    }
    @isTest static void testRunTemplateRollup(){
        setCustomSetting();
        createTestData();
        
        Form_Template__c template = [SELECT Id, External_Reference__c FROM Form_Template__c LIMIT 1];
        List<Form_Question__c> questions = [SELECT Id, Name, Form_Section__c, Order__c, Question__c, Label_Visible__c, Text_Alignment__c, Font_Size__c, Font_Color__c, Value_Set__c, Include_Comment__c, Include_Photo__c, Type__c, Form_Template__c,Layout_Item__c,Display_Rich_Text__c, Conditions__c FROM Form_Question__c WHERE Form_Template__c = :template.Id];
        Test.startTest();
        System.debug('In Test Template Id: ' + template.Id);
        System.debug('Questions: ' + questions);
        Boolean result = neuraFormExportController.runTemplateRollup(new List<String>{template.Id});
        Test.stopTest();
        Form_Template__c newTemplate = [SELECT Id, Pages_JSON__c, Sections_JSON__c, Questions_JSON__c, External_Reference__c FROM Form_Template__c LIMIT 1];
        System.assert(newTemplate.Pages_JSON__c != null, 'Pages_JSON__c should not be null');
        System.assert(newTemplate.Sections_JSON__c != null, 'Sections_JSON__c should not be null');
        System.assert(newTemplate.Questions_JSON__c != null, 'Questions_JSON__c should not be null');
    }

    // Test method for fetchTemplatesData
    @isTest static void testFetchTemplatesData() {
        createTestData();
        Form_Template__c template = [SELECT Id, External_Reference__c FROM Form_Template__c LIMIT 1];

        Test.startTest();
        String jsonData = neuraFormExportController.fetchTemplatesData(new List<String>{template.Id});
        Test.stopTest();
        
        // Asserts
        System.assertNotEquals(null, jsonData, 'The JSON data should not be null');
    }

    // Test method for importTemplates
    @isTest static void testImportTemplates() {
        createTestData();
        // Determine if in NameSpace context or not
        String namespacePrefix = NeuraFormUtils.getNamespacePrefix();
        String fieldName = namespacePrefix + 'External_Reference__c';

        Form_Template__c template = [SELECT Id, External_Reference__c FROM Form_Template__c LIMIT 1];
        String jsonContent = neuraFormExportController.fetchTemplatesData(new List<String>{template.Id});

        Test.startTest();
        neuraFormExportController.ImportResult result = neuraFormExportController.importTemplates(jsonContent);
        Test.stopTest();

        System.assertNotEquals(null, result, 'ImportResult should be returned');
        System.assertEquals(1, result.templates.size(), 'There should be one template processed');
        System.assertEquals(template.Id, result.templates[0].External_Reference__c, 'The external reference should match the source Id');
        System.assertEquals(0, result.warnings.size(), 'A round-trip of a known-good template should produce no warnings');
        // The original record was inserted without an External_Reference, so
        // the export sets it on the in-memory copy only. Re-importing matches
        // nothing in the DB (existing row still has null External_Reference)
        // and inserts a new record.
        System.assertEquals(1, result.createdCount, 'Round-trip should create a new row when the source had a null External_Reference');
        System.assertEquals(0, result.updatedCount);
    }

    // Test method to cover the exception scenario in importTemplates
    @isTest static void testImportTemplatesExceptionScenario() {
        String badJsonContent = 'not a valid JSON string';
        try {
            Test.startTest();
            neuraFormExportController.importTemplates(badJsonContent);
            Test.stopTest();
            System.assert(false, 'Exception should have been thrown');
        } catch (AuraHandledException e) {
            System.assert(true, 'Expected exception was thrown');
        }
    }

    // Test method to cover the exception scenario in fetchTemplatesData
    @isTest static void testFetchTemplatesDataExceptionScenario() {
        try {
            Test.startTest();
            neuraFormExportController.fetchTemplatesData(null);
            Test.stopTest();
            System.assert(false, 'Exception should have been thrown');
        } catch (AuraHandledException e) {
            System.assert(true, 'Expected exception was thrown');
        }
    }

    // Test method for package-private methods
    @isTest
    static void testPackagePrivateMethods() {
        // Test generateFieldList method
        String fieldList = neuraFormExportController.generateFieldList('Form_Template__c');
        System.assertNotEquals(null, fieldList, 'The field list should not be null');

        // Test addExternalIdValues method
        createTestData();
        List<Form_Template__c> templates = [SELECT Id, External_Reference__c, (SELECT Id, External_Reference__c FROM Form_Pages__r), (SELECT Id, External_Reference__c FROM Form_Sections__r), (SELECT Id, External_Reference__c FROM Form_Questions__r) FROM Form_Template__c];
        templates = neuraFormExportController.addExternalIdValues(templates);
        System.assertEquals(null, templates[0].Id, 'Template ID should be null after method call');
        System.assertNotEquals(null, templates[0].External_Reference__c, 'External reference should not be null');

        // Test removeStrings method
        List<String> listToClean = new List<String>{'ownerid', 'createdbyid', 'isdeleted', 'field1', 'field2'};
        Set<String> removalList = new Set<String>{'ownerid', 'createdbyid', 'isdeleted'};
        List<String> cleanedList = neuraFormExportController.removeStrings(listToClean, removalList);
        System.assertEquals(2, cleanedList.size(), 'Cleaned list should have 2 fields');
    }
}